spring:
  messages:
    basename: messages
  mvc:
    view:
      prefix: /
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true